kubectl delete replicaset  eapidpicustomerordereventsprocessor-v009 -n rpi-boots-pharmacy-s
kubectl delete replicaset  eapirtbukofhcosmosdb-v003 -n rpi-boots-pharmacy-s
kubectl delete replicaset  eapirtbukofhcosmosdb-v004 -n rpi-boots-pharmacy-s
kubectl delete replicaset  eapirtbukofhcosmosdb-v005 -n rpi-boots-pharmacy-s
kubectl delete replicaset  spinnakeraksreportserviceemea-v026 -n rpi-boots-pharmacy-s
kubectl delete replicaset  spinnakeraksreportserviceemea-v027 -n rpi-boots-pharmacy-s
kubectl delete replicaset  spinnakeraksreportserviceemea-v028 -n rpi-boots-pharmacy-s
kubectl delete replicaset  eapirtbukjsecretsvalidation-v000 -n rpi-boots-retail-s    
kubectl delete replicaset  eapirtbukjsecretsvalidation-v001 -n rpi-boots-retail-s    
kubectl delete replicaset  eapirtbukjsecretsvalidation-v002 -n rpi-boots-retail-s    
kubectl delete replicaset  eapirtbuknodjsecretsvalidation-v000 -n rpi-boots-retail-s 
kubectl delete replicaset  eapirtbuknodjsecretsvalidation-v001 -n rpi-boots-retail-s 
kubectl delete replicaset  eapirtbuknodjsecretsvalidation-v002 -n rpi-boots-retail-s 
kubectl delete replicaset  eapirtbukpricecosmoschangefeed-v009 -n rpi-boots-retail-s 
kubectl delete replicaset  eapirtbukpricecosmoschangefeed-v010 -n rpi-boots-retail-s 
kubectl delete replicaset  eapirtbukpricecosmoschangefeed-v011 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukpricingdataload-v016 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukpricingdataload-v017 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukpricingdataload-v018 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukpricingpublishdb-v015 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukpricingreceiver-v005 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukpricingreceiver-v006 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukpricingreceiver-v007 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukproductsdatatransform-v006 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukproductsdatatransform-v007 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukproductsdatatransform-v008 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukproductspublishdb-v008 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukproductspublishdb-v009 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukproductspublishdb-v010 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukproductsreceiver-v012 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukproductsreceiver-v013 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukproductsreceiver-v014 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukpromotionsreceiver-v000 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukpromotionsreceiver-v001 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukpromotionsreceiver-v002 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukrprshousekeeping-v020 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukrprshousekeeping-v021 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbukrprshousekeeping-v022 -n rpi-boots-retail-s
kubectl delete replicaset  eapirtbuksvocpostaldataload-v000 -n rpi-boots-retail-s
